### ISSUE TITLE
Demo of Lip Sync Performance

### ISSUE THREAD

**Issue by aadr1024** [HallowSiddharth/VoiceCraftAI#18]
Hey, it would be great to see a video of where this library is at and let new users or contributors see what they can make out of the library.

**Comment by v1sh-afk** [comment]
Hey, thanks for the suggestion! A demo video is a great idea to show what VoicecraftAI can do. We’re planning to put together a quick walkthrough of the pipeline, including a sample of the voice dubbing process using our open-source models like MuseTalk(https://github.com/TMElyralab/MuseTalk) and Wav2Lip (https://github.com/Rudrabha/Wav2Lip)

If you're interested in contributing, this is the current direction we're working on. We’re also in the process of migrating to a new version of RVC, which means the project structure will change soon. You may want to wait for the updated structure before diving in. Thanks again for your interest, and we look forward to sharing the demo video soon!
